# 定义服务端口号
server:
  port: 8761

#指定应用名称
spring:
  application:
    name: eureka-server

# 指定当前eureka客户端的注册地址，也就是eureka服务的提供方，当前配置的服务的注册服务方
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false #自身 不在向eureka注册
    fetch-registry: false #启动时禁用client的注册;注册中心职责是维护服务实例，false：不检索服务。
  instance:
    hostname: localhost

